vich_uploader:
    db_driver: orm

    mappings:
        courseImage:
            uri_prefix: /images/course
            upload_destination: '%kernel.project_dir%/assets/images/course'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        user:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/assets/images/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        news:
            uri_prefix: /images/news
            upload_destination: '%kernel.project_dir%/assets/images/news'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        pdf:
            uri_prefix: /images/program
            upload_destination: '%kernel.project_dir%/assets/images/program'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
